# Minimal detekt configuration
# Builds upon default config with specific customizations

build:
  maxIssues: 0
  excludeCorrectable: false
  weights:
    EmptyCatchBlock: 1
    TooGenericExceptionCaught: 1

config:
  validation: true
  warningsAsErrors: false
  excludes: ''
